# Site settings
title: Mobile Academy
email: hello@dudek.mobi
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mobile-academy.github.io"
twitter_username: mobacademy
github_username:  mobile-academy

sass:
    sass_dir: _sass

# Collections

collections:
  upcoming:
    output: true
  past:
    output: true

# Build settings
markdown: kramdown
