# Site settings
title: Mobile Academy
email: hello@dudek.mobi
description: > # this means to ignore newlines until "baseurl:"
  We're a group of passionates who love creating great software.
  We believe that there's no better way to learn other than practicing.
  That's why share our knowledge and experience through the workshops formula.
  That's why we've founded Mobile Academy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mobile-academy.github.io"
twitter_username: mobacademy
github_username:  mobile-academy

sass:
    sass_dir: _sass

# Collections

collections:
  base_descriptions:
    output: true
    output_ext: html
  upcoming:
    output: true
    output_ext: html
  past:
    output: true

# Build settings
markdown: kramdown
